# https://www.playframework.com/documentation/latest/Configuration
# allowing localhost

#env variables
google.clientId = ${?SUBLIMIS_CLIENT_ID}


play.filters.enabled += "play.filters.cors.CORSFilter"
play.filters.enabled += "play.filters.csrf.CSRFFilter"

play.modules.enabled += "modules.RedisModule"

db.default.driver=org.postgresql.Driver
# db.default.url="jdbc:postgresql://99.240.208.73:5432/sublimismain"
db.default.url="jdbc:postgresql://10.0.0.200:5432/sublimismain"

db.default.username=sublimis
db.default.password=${?SUBLIMIS_DB_PASS}

redis.default.password=${?SUBLIMIS_REDIS_PASS}
redis.default.ip="10.0.0.200"
# redis.default.ip="99.240.208.73"

play.filters.cors {
  allowedOrigins = ["http://localhost:5173","http://localhost:4173" ]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  supportsCredentials = true
}

play.filters.csrf {
  enabled = false
  bypassCorsTrustedOrigins = true
}

# arbitrary pool size that i should probably change later
fixedConnectionPool = 9

# using other threads for database services to not block main thread
postgres.dispatcher {
  executor = "thread-pool-executor"
  throughput = 1
  thread-pool-executor {
    fixed-pool-size = ${fixedConnectionPool}
  }
}

redis.dispatcher {
  executor = "thread-pool-executor"
  throughput = 1
  thread-pool-executor {
    fixed-pool-size = ${fixedConnectionPool}
  }
}
