# https://www.playframework.com/documentation/latest/Configuration
# allowing localhost
play.filters.enabled += "play.filters.cors.CORSFilter"

db.default.driver=org.postgresql.Driver
# db.default.url="jdbc:postgresql://99.240.208.73:5432/testdb"
db.default.url="jdbc:postgresql://10.0.0.108:5432/testdb"
db.default.username=testuser
db.default.password=mongus123

play.filters.cors {
  allowedOrigins = ["http://localhost:5173"]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
}

# arbitrary pool size that i should probably change later
fixedConnectionPool = 9

# using other threads for database services to not block main thread
database.dispatcher {
  executor = "thread-pool-executor"
  throughput = 1
  thread-pool-executor {
    fixed-pool-size = ${fixedConnectionPool}
  }
}
